### ISSUE TITLE
Update std and check if socket is closed

### ISSUE THREAD

**Issue by ThomasOrlita** [Jack-Works/async-call-rpc#32]
I am checking out your library and so far it looks promising!

However, after setting up the deno server, it would crash with `error: Uncaught (in promise) ConnectionReset: Socket has already been closed`.

I've added a check to return if the socket is closed:

https://github.com/Jack-Works/async-call-rpc/blob/12cbb823f67d7da27a491f042ba1a29a67e1d3f6/utils/deno/websocket.server.ts#L28-L31

    if (websocket.isClosed) return

----

Also, the std is quite outdated, so I've updated it to `@0.106.0`

https://github.com/Jack-Works/async-call-rpc/blob/12cbb823f67d7da27a491f042ba1a29a67e1d3f6/utils/deno/websocket.server.ts#L1-L2

----

This seems to work now, but still might need to be tested. Please let me know what you think and if this can be updated here.

**Comment by Jack-Works** [comment]
Hi! Thanks for your interest! You can create a PR to fix this or if you don't want to, I can do it.

**Comment by ThomasOrlita** [comment]
I've sent the PR for the `isClosed` bug.
But keeping the same _std_ version as the functions/types such as `acceptWebSocket`, `WebSocket` are deprecated in deno stable.

**Comment by Jack-Works** [comment]
I have published 6.0.1
