### ISSUE TITLE
Warns about using "then" when resolving a Promise with result of AsyncCall

### ISSUE THREAD

**Issue by tuxcrafting** [Jack-Works/async-call-rpc#36]
When resolving a promise with the return value of `AsyncCall` (or returning from an async function, for that matter), the runtime tries to access the `then` property to see if it has to follow it or not. While the returned value is undefined, and hence the value is returned, there is still a warning message printed, which is annoying.

Setting the `thenable` option makes it so that the promise resolving thinks it is actually a Promise object, and hence tries to call the `then` function, resulting in a spurious `then` RPC call.

Example, in Deno:

```ts
import { AsyncCall } from 'https://cdn.jsdelivr.net/npm/async-call-rpc@v6.0.1/out/base.mjs';

async function f() {
    return AsyncCall({}, {
        channel: {
            on: null,
            send: null,
        },
    } as any);
}

await f();
```

Produces the output

```
TypeError: RPC used as Promise: Error 3: https://github.com/Jack-Works/async-call-rpc/wiki/Errors#3
    at Object.get (https://cdn.jsdelivr.net/npm/async-call-rpc@v6.0.1/out/base.mjs:679:29)
    at f (file:///tmp/blah.ts:4:12)
    at file:///tmp/blah.ts:12:7
```

**Comment by Jack-Works** [comment]
When the `thenable` is missing, it will print a warning when the instance is used as a Promise. You can set `thenable: false` to disable this warning and still let it return undefined.

**Comment by tuxcrafting** [comment]
Ah, I see. I missed the part of the documentation that mentions it can be explicitly set to false to disable this. Thanks!
